### ISSUE TITLE
UI error in shop.html

### ISSUE THREAD

**Issue by RohitKumar-200** [Bookshlf-in/Coming-Soon#5]
Footer of the website is not fixed, it scrolls with the page.

Images for reference:
![Screenshot (349)](https://user-images.githubusercontent.com/55583961/133979666-8b6d058f-1e5e-458e-ba1a-f8df60db2dea.png)

![Screenshot (350)](https://user-images.githubusercontent.com/55583961/133979685-60ad465f-1b4d-4b20-bc7c-accc98190e89.png)

**Comment by iam-sarthak** [comment]
Remove **bottom: 0px;** from CSS
![Capture](https://user-images.githubusercontent.com/80532254/133983080-f23e00d4-fccf-4a6e-963b-1cfd2ef6ef70.PNG)

**Comment by RohitKumar-200** [comment]
Thanks, @iam-sarthak for your suggestion. changing position to static solved the issue.
And thanks, @Nilesh-chaudhary for solving this issue, and creating a PR #9
