### ISSUE TITLE
Wrong href link

### ISSUE THREAD

**Issue by RohitKumar-200** [Bookshlf-in/Coming-Soon#6]
Home page link in navbar redirects to https://bookshlf.in/bookshlf.in, which is wrong. It should redirect to either https://bookshlf.in/index.html or simply https://bookshlf.in/

Images for reference:

![1](https://user-images.githubusercontent.com/55583961/133982393-df136fa1-5e2f-4353-98f4-705c7c832619.png)

![2](https://user-images.githubusercontent.com/55583961/133982422-7d197b50-5573-4294-93a6-c46daf3f5218.png)

**Comment by suman-somu** [comment]
i am trying to work on this . 
waiting for response .
