### ISSUE TITLE
Missing favicon in website

### ISSUE THREAD

**Issue by RohitKumar-200** [Bookshlf-in/Coming-Soon#7]
![1](https://user-images.githubusercontent.com/55583961/133985121-8aab068f-bb56-4d01-bce0-3c30bd6c07aa.png)

Favicon link : https://img.bookshlf.in/logo/favicon.ico

**Comment by suman-somu** [comment]
working on this . 
waiting for reply .

**Comment by RohitKumar-200** [comment]
Thanks for your contribution

**Comment by suman-somu** [comment]
u r welcome .
